# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'native_ios_animation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for native_ios_animation
  pod 'SideMenu'
  pod 'lottie-ios'
  pod 'GDPerformanceView-Swift', '~> 1.2.0'

end
